baseURL: ''
languageCode: en-us
title: Australian Imaging Service
contentDir: content

module:
  # uncomment line below for temporary local development of module
  # or when using a 'theme' as a git submodule
  # replacements: "github.com/colinwilson/lotusdocs -> lotusdocs"
  imports:
    path: "github.com/colinwilson/lotusdocs"
    disable: false
  imports:
    path: "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable: false

markup:
  tableOfContents:
    endLevel: 3
    startLevel: 1
  goldmark:
    renderer:
      unsafe: true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  goldmark.parser:
    parser.attribute:
      block: true

theme: lotusdocs

params:
  google_fonts: [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  sans_serif_font: "Inter"     # Default is System font
  secondary_font: "Inter"     # Default is System font
  mono_font: "Fira Code" # Default is System font

  footer:
    copyright: "© :YEAR: Lotus Labs. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
    # version: true # includes git commit info

  social:
    github: ""        # YOUR_GITHUB_ID or YOUR_GITHUB_URL
    twitter: ""       # YOUR_TWITTER_ID
    # instagram: "colinwilson"     # YOUR_INSTAGRAM_ID
    # rss: true                    # show rss icon with link

  docs: # Parameters for the /docs 'template'
    title          : "Lotus Docs Example Site"           # default html title for documentation pages/sections
    darkMode       : true                                # enable dark mode option? default false

    prism          : true                                # enable syntax highlighting via Prism

    prismTheme     : "solarized-light"                           # (optional) - Set theme for PrismJS. Options include: lotusdocs (default), solarized-light, twilight, lucario

    # gitinfo
    repoURL        : "https://github.com/colinwilson/lotusdocs.dev"  # Git repository URL for your site [support for GitHub, GitLab, and BitBucket]
    repoBranch     : "release"
    editPage       : true                                # enable 'Edit this page' feature - default false
    lastMod        : true                                # enable 'Last modified' date on pages - default false
    lastModRelative: true                                # format 'Last modified' time as relative - default true

    sidebarIcons   : true                                # enable sidebar icons? default false
    breadcrumbs    : true                                # default is true
    backToTop      : true                                # enable back-to-top button? default true

    # ToC
    toc            : true                                # enable table of contents? default is true
    tocMobile      : true                                # enable table of contents in mobile view? default is true
    scrollSpy      : true                                # enable scrollspy on ToC? default is true

    # front matter
    descriptions   : true                                # enable front matter descriptions under content title?
    titleIcon      : true                                # enable front matter icon title prefix? default is false

    # content navigation
    navDesc        : true                                # include front matter descriptions in Prev/Next navigation cards
    navDescTrunc   : 30                                  # Number of characters by which to truncate the Prev/Next descriptions

    listDescTrunc  : 100                                 # Number of characters by which to truncate the list card description

    # Link behaviour
    intLinkTooltip : true                                # Enable a tooltip for internal links that displays info about the destination? default false
    # extLinkNewTab  : false                             # Open external links in a new Tab? default true
    # logoLinkURL: ""                                    # Set a custom URL destination for the top header logo link.

  flexsearch: # Parameters for FlexSearch
    enabled: trueS

menus:
  primary:
  - name: Example
    pageRef: /docs
    weight: 10
